/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountryCodeIndexRouteImport } from './routes/country/$code/index'
import { Route as CountryCodeWeatherRouteImport } from './routes/country/$code/weather'

const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeIndexRoute = CountryCodeIndexRouteImport.update({
  id: '/country/$code/',
  path: '/country/$code/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeWeatherRoute = CountryCodeWeatherRouteImport.update({
  id: '/country/$code/weather',
  path: '/country/$code/weather',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRoute
  '/country/$code/weather': typeof CountryCodeWeatherRoute
  '/country/$code': typeof CountryCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRoute
  '/country/$code/weather': typeof CountryCodeWeatherRoute
  '/country/$code': typeof CountryCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRoute
  '/country/$code/weather': typeof CountryCodeWeatherRoute
  '/country/$code/': typeof CountryCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/compare'
    | '/country/$code/weather'
    | '/country/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/compare' | '/country/$code/weather' | '/country/$code'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/compare'
    | '/country/$code/weather'
    | '/country/$code/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CompareRoute: typeof CompareRoute
  CountryCodeWeatherRoute: typeof CountryCodeWeatherRoute
  CountryCodeIndexRoute: typeof CountryCodeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country/$code/': {
      id: '/country/$code/'
      path: '/country/$code'
      fullPath: '/country/$code'
      preLoaderRoute: typeof CountryCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country/$code/weather': {
      id: '/country/$code/weather'
      path: '/country/$code/weather'
      fullPath: '/country/$code/weather'
      preLoaderRoute: typeof CountryCodeWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CompareRoute: CompareRoute,
  CountryCodeWeatherRoute: CountryCodeWeatherRoute,
  CountryCodeIndexRoute: CountryCodeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
